version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"

  node-app:
    build: .
    container_name: "node-app"
    ports:
      - "3100:3100"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
       - .env
